language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

env:
  global:
    - APP_ENV=staging
    - APP_KEY=base64:IogPPlUJX4x/eEXC44rcLOXTZa9WO/75dvbmONVe/9k=
    - APP_DEBUG=true
    - APP_LOG_LEVEL=debug

    - DB_CONNECTION=sqlite_testing
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

    - TWITTER_CONSUMER_KEY=9POH0moFpD1Ko2S5i12Rqwbps
    - TWITTER_ACCESS_TOKEN=6515352-Ci9VVdJFgwjhzi3VoBsWNpQgWpl5YQEehrAocSi9Gj

    - TWITTER_FRIENDS_CACHE_EXPIRE=360
    - TWITTER_USER=ed_crompton

before_install:
    - composer install --no-interaction
    - php artisan migrate:install
