version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8181:80"
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  composer:
    build: docker/composer/
    volumes:
      - .:/app
    command: install

  php:
    build: docker/php/
    environment:
       APP_ENV: "testing"
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  chrome:
    image: robcherry/docker-chromedriver
    networks:
       - app-network
    environment:
       CHROMEDRIVER_WHITELISTED_IPS: ""
       CHROMEDRIVER_PORT: "9515"
    cap_add:
       - "SYS_ADMIN"

networks:
  app-network:
